/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxList: typeof import('./src/components/BoxList.vue')['default']
    FindingDisplay: typeof import('./src/components/FindingDisplay.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ImageCanvas: typeof import('./src/components/ImageCanvas.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
  }
}
